name: Build Fjordock Alpine Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  fjordock-alpine-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multiarch
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Helper to convert docker org to lowercase
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}

      - name: Login to GitHub Container Registry
        if: ${{ env.ACT != 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multiarch Alpine image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ env.ACT != 'true' }}
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/alpine:3.22.1
          provenance: false
          sbom: false
